# Generated by Django 5.0.6 on 2024-07-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dob',
            new_name='date',
        ),
    ]
